name: yujai
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cloud_firestore: 
  firebase_analytics: ^5.0.11
  flutter_linkify: ^5.0.2
  image_picker: ^0.8.0+3
  firebase_storage: 
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  geolocator: ^7.1.0
  uuid: ^3.0.4
  image: ^3.0.2
  animator: ^1.0.0+5
  cupertino_icons: ^1.0.3
  cupertino_tabbar: ^1.1.1
  path_provider:
  path_provider_platform_interface: ^2.0.0
  firebase_messaging: ^10.0.2
  timeago: ^2.0.26
  cached_network_image: ^3.0.0
  flutter_svg: ^0.21.0+1
  xml: ^5.0.0
  groovin_material_icons:
  http: ^0.13.1
  firebase_dynamic_links: ^0.5.0+1
  # rxdart: ^0.23.1
  flutter_secure_storage: ^3.2.1+1
  country_code_picker: ^1.1.7
  pin_view: ^1.0.1
  firebase_core:
  intl: 0.17.0
  flutter_datetime_picker:
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git
  autocomplete_textfield: ^1.7.3
  #dash_chat: ^1.0.19
  material_design_icons_flutter: ^4.0.5145
  file_picker: ^3.0.2+2
  flutter_email_sender: ^3.0.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.6+3
  imagebutton: ^0.0.6
  flutter_rounded_date_picker: ^1.0.4
  datetime_picker_formfield: ^1.0.0
  geocoder: ^0.2.1
  geocoding: ^2.0.0
  location: ^4.3.0
  location_web: ^3.1.1
  unicorndial: "^1.1.5"
  # algolia: ^0.1.6+1
  google_maps_place_picker: ^2.0.0-nullsafety.3
  google_maps_webservice: ^0.0.16
  google_maps_flutter: ^2.0.6
  tuple: ^2.0.0
  quiver: ^3.0.0
  #permission_handler: ^5.0.1+1
  url_launcher: ^6.0.9
  webview_flutter: ^0.3.14+1
  # add_thumbnail: ^0.0.2
  shimmer: ^1.1.2
  flutter_dropdown: ^0.0.8
  flutter_chat_bubble: ^1.0.2
  lite_rolling_switch: ^0.1.1
  # in_app_review: ^1.0.4
  countdown_flutter: ^0.1.2
  multi_image_picker: ^4.7.14
  carousel_slider: ^3.0.0
  currency_textfield: ^1.0.3
  flutter_cache_manager: ^3.1.1
  adobe_xd: ^2.0.0+1
  flutter_colorpicker: ^0.3.5
  date_range_form_field: ^1.0.1
  select_dialog:
  icon_picker: "^1.1.0"
  flutter_iconpicker: ^3.0.2
  flutter_staggered_grid_view: ^0.3.3
  # expandable_text: 1.2.0
  transparent_image:
  empty_widget: ^0.0.2
  flutter_fab_dialer: ^0.1.1
  flutter_boom_menu:
  date_field: ^1.0.0
  percent_indicator: 
  flutter_slidable: ^0.6.0
  new_version: ^0.0.6
  flutter_google_places: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash:

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Italic.ttf
  assets:
     - assets/images/
     - assets/translations/de.json # <--- THIS LINE WAS ADDED
     - assets/translations/en.json # <--- THIS LINE WAS ADDED